# Configuration for standalone FreeEnv + FreeAgent runs.
task_name: free-session
output_path: exps/free_env

llm_name: "human"

# Tools to load into the environment toolbox.
tools:
  - rewrite
  - bash
  - submit:
      eval_on_submit: False  # Here we only terminate after submission, no auto-eval.

task_data:
  env_type: FreeEnv
  image: ubuntu:22.04
  local_path: /home/macote/src/debug-gym/data/mini_nightmare/pandas_dataframe
  workspace_dir: /testbed

terminal:
  type: docker

agent:
  type: froggy
  max_steps: 20
